import { IProduct } from "../models/IProduct";

export const ProductData:IProduct[] = [{"id":1,"title":"Open Season 2","price":63},
{"id":2,"title":"Picnic at Hanging Rock","price":1},
{"id":3,"title":"Danse: The Paris Opera Ballet, La (La Danse - Le ballet de l'Opéra de Paris)","price":43},
{"id":4,"title":"Fall From Grace","price":19},
{"id":5,"title":"Carry On, Constable","price":7},
{"id":6,"title":"Canvas","price":14},
{"id":7,"title":"Libel","price":44},
{"id":8,"title":"Avenger ","price":5},
{"id":9,"title":"Tucker & Dale vs Evil","price":95},
{"id":10,"title":"First Cousin Once Removed","price":29},
{"id":11,"title":"Cheaper by the Dozen","price":18},
{"id":12,"title":"4th Man, The (Fourth Man, The) (Vierde man, De)","price":20},
{"id":13,"title":"Emperor Waltz, The","price":11},
{"id":14,"title":"Night at the Museum: Secret of the Tomb","price":59},
{"id":15,"title":"Fat Head","price":85},
{"id":16,"title":"Charlotte's Web 2: Wilbur's Great Adventure","price":9},
{"id":17,"title":"Accepted","price":47},
{"id":18,"title":"Bachelorette","price":24},
{"id":19,"title":"Letzte schöne Herbsttag, Der","price":10},
{"id":20,"title":"Premium Rush","price":94},
{"id":21,"title":"Blue and the Gray, The","price":61},
{"id":22,"title":"Heaven Can Wait","price":98},
{"id":23,"title":"Las Vegas Story, The","price":66},
{"id":24,"title":"Man of the Century","price":13},
{"id":25,"title":"Cotton Mary","price":58},
{"id":26,"title":"Cat and the Canary, The","price":1},
{"id":27,"title":"10 Things I Hate About You","price":66},
{"id":28,"title":"12 Days of Terror","price":1},
{"id":29,"title":"Rockabilly Vampire","price":76},
{"id":30,"title":"Number Seventeen (a.k.a. Number 17)","price":98},
{"id":31,"title":"Sleuth","price":47},
{"id":32,"title":"It! The Terror from Beyond Space","price":9},
{"id":33,"title":"Squall, The","price":27},
{"id":34,"title":"Jesse Stone: Stone Cold","price":61},
{"id":35,"title":"Pleasure Garden, The","price":3},
{"id":36,"title":"Devdas","price":60},
{"id":37,"title":"The Wayward Girl","price":17},
{"id":38,"title":"Soloist, The","price":64},
{"id":39,"title":"Thieves Like Us","price":29},
{"id":40,"title":"Care Bears Movie II: A New Generation","price":18},
{"id":41,"title":"I Was A Communist for the FBI","price":99},
{"id":42,"title":"Rent-A-Cop","price":9},
{"id":43,"title":"Kahaani","price":65},
{"id":44,"title":"Orfeu","price":86},
{"id":45,"title":"Days of Wine and Roses","price":68},
{"id":46,"title":"Peacemaker, The","price":38},
{"id":47,"title":"Giallo","price":6},
{"id":48,"title":"Big Sleep, The","price":53},
{"id":49,"title":"Pacifier, The","price":30},
{"id":50,"title":"Incredible Hulk Returns, The","price":14},
{"id":51,"title":"Live Forever","price":70},
{"id":52,"title":"Magic of Ordinary Days, The","price":64},
{"id":53,"title":"Suriyothai (a.k.a. Legend of Suriyothai, The)","price":9},
{"id":54,"title":"Zatoichi Meets the One-Armed Swordsman (Shin zatô Ichi: Yabure! Tôjin-ken) (Zatôichi 22)","price":95},
{"id":55,"title":"All Passion Spent","price":10},
{"id":56,"title":"Border Café","price":69},
{"id":57,"title":"Caught Inside","price":70},
{"id":58,"title":"Passage to Marseille","price":20},
{"id":59,"title":"Wings of Desire (Himmel über Berlin, Der)","price":74},
{"id":60,"title":"Omen, The","price":86},
{"id":61,"title":"3 Extremes (Three... Extremes) (Saam gaang yi)","price":61},
{"id":62,"title":"Hostage","price":15},
{"id":63,"title":"Black Field","price":100},
{"id":64,"title":"Jönssonligan spelar högt","price":39},
{"id":65,"title":"Ugly","price":21},
{"id":66,"title":"Gossip","price":31},
{"id":67,"title":"For Pete's Sake","price":20},
{"id":68,"title":"Hole, The (Dong)","price":7},
{"id":69,"title":"Merchant of Four Seasons, The (Händler der vier Jahreszeiten)","price":27},
{"id":70,"title":"Read It and Weep","price":44},
{"id":71,"title":"Dirty Deeds","price":10},
{"id":72,"title":"Raze","price":11},
{"id":73,"title":"Somebody Up There Likes Me","price":51},
{"id":74,"title":"Stonehenge Apocalypse","price":50},
{"id":75,"title":"Idol of the Crowds","price":31},
{"id":76,"title":"Cremaster 5","price":18},
{"id":77,"title":"Introduction to Physics, An","price":16},
{"id":78,"title":"Different from You and Me (Anders als du und ich) ","price":84},
{"id":79,"title":"Double Dare","price":69},
{"id":80,"title":"Solaris","price":34},
{"id":81,"title":"Betrayed, The","price":16},
{"id":82,"title":"Pina","price":49},
{"id":83,"title":"Summer Hours (Heure d'été, L')","price":47},
{"id":84,"title":"Guns of Navarone, The","price":64},
{"id":85,"title":"Journey to Italy (Viaggio in Italia) (Voyage to Italy) (Voyage in Italy)","price":49},
{"id":86,"title":"Flipped","price":14},
{"id":87,"title":"Dinner Game, The (Dîner de cons, Le)","price":65},
{"id":88,"title":"La guerre des tuques","price":26},
{"id":89,"title":"Night of the Demons","price":99},
{"id":90,"title":"Death in Venice (Morte a Venezia)","price":85},
{"id":91,"title":"Panama Hattie","price":61},
{"id":92,"title":"The Hire: Ticker","price":75},
{"id":93,"title":"Undisputed II: Last Man Standing","price":46},
{"id":94,"title":"Whitey: United States of America v. James J. Bulger","price":54},
{"id":95,"title":"Space Is The Place","price":10},
{"id":96,"title":"Marriage Circle, The","price":83},
{"id":97,"title":"Panic in Year Zero!","price":62},
{"id":98,"title":"Toward the Unknown","price":96},
{"id":99,"title":"Our Little Girl","price":8},
{"id":100,"title":"Colpo in canna","price":98}] 